### Kaplan-Meier curve for mortality and hospitalisation
### Produce CCU049_01 Figure 1
### Yi Mu


install.packages("survival")
install.packages("tidycmprsk")
install.packages("casebase")
install.packages("Rtools")
install.packages("cmprsk")
install.packages("ggsurvfit")
install.packages("riskRegression")

library(data.table)
library(dplyr)
library(survival)
library(survminer)

library(riskRegression)
library(survival)
library(survminer)
library(tidycmprsk)
library(cmprsk)
library(dplyr)
library(casebase)
library(ggplot2)
library(ggsurvfit)
library(magrittr)


#### Trying Johan and Chris code to produce survival plot ####

load("D:/PhotonUser/My Files/Home Folder/ccu049/survival/all_death.rdata")
load("D:/PhotonUser/My Files/Home Folder/ccu049/survival/all_hosp.rdata")

### Data structure: 

## Mortality

# id, 
# two_yr_death (1 if the patient died within 2 years of follow-up), 
# two_yr_followup_day_1 (days of follow-up +1 in case days of follow-up is 0)
# followup_mon (months of follow-up = two_yr_followup_day_1/30.44)
# group ("Long Covid", "COVID only, no Long Covid", "Contemporary non-COVID", "Pre-pandemic" )
# age (only for filtering)

## Hospitalisation

# id, 
# two_yr_hos (1 if the patient was hospitalised within 2 years of follow-up), 
# two_yr_followup_day_1 (days of follow-up +1 in case days of follow-up is 0)
# followup_mon (months of follow-up = two_yr_followup_day_1/30.44)
# group ("Long Covid", "COVID only, no Long Covid", "Contemporary non-COVID", "Pre-pandemic" )
# age (only for filtering)



test <- all_two_death %>% filter(age>=18)
test <- all_two_hosp %>% filter(age>=18)

#make sure the on the figure only shows 2-year and not more
test$followup_mon[test$followup_mon>24] <- 24
sum(test$followup_mon>24) # just check if sum is 0 (should be)

#folder_path <- "D:/PhotonUser/My Files/Home Folder/ccu049/survival"

## Mortality

survp_death <- survfit(Surv(followup_mon,two_yr_death) ~ group,data=test)

# Note: I didn't used the risk table and cumulative events table generated by this code (risk.table=FALSE, 
# cumevents=FALSE), as I had to round the number in the table to the nearest 5. 
ggsurvplot(survp_death, pval = FALSE,
           conf.int = 0.95,
           ylim=c(0, 0.05), # Have to manually adjust this to scale plot
           xlim=c(0,24), # Probably makes sense to cut off plot at 28 days, as that's the garanteed min fu_time
           break.time.by = 6,
           xlab = "Time (months)",
           ylab = "Cumulative Incidence",
           #pval.coord = c(0,  my_ymax-(my_ymax*0.1)),
           title = "A. Mortality",
           font.title = c(14, "bold", "black"),
           legend = c(0.15, 0.85),
           legend.title = "",
           font.legend = 9,
           legend.labs = c("COVID only, no Long Covid","Long Covid","Contemporary non-COVID", "Pre-pandemic"),
           risk.table = TRUE,
           cumevents = TRUE,
           font.y = 13,
           font.x = 13,
           fontsize = 3,
           censor.size=0.2,
           size = 0.2,
           fun = "event",
           surv.scale = "percent") # + theme(axis.text =  element_text(size = 12))


## Hospitalisation

survp_hos <- survfit(Surv(followup_mon,two_yr_hos) ~ group,data=test)


# Note: I didn't used the risk table and cumulative events table generated by this code (risk.table=FALSE, 
# cumevents=FALSE), as I had to round the number in the table to the nearest 5. 

ggsurvplot(survp_hos, pval = FALSE, conf.int = 0.95,
           ylim=c(0, 0.45), # Have to manually adjust this to scale plot
           xlim=c(0, 24), # Probably makes sense to cut off plot at 28 days, as that's the gauranteed min fu_time
           break.time.by = 6,
           xlab = "Time (months)",
           ylab = "Cumulative Incidence",
           #pval.coord = c(0,  my_ymax-(my_ymax*0.1)),
           title = "B. Hospitalisation",
           font.title = c(14, "bold", "black"),
           legend = c(0.15, 0.85),
           legend.title = "",
           font.legend = 9,
           legend.labs = c("COVID only, no Long Covid","Long Covid","Contemporary non-COVID", "Pre-pandemic"),
           risk.table = TRUE,
           cumevents = TRUE,
           font.y = 13,
           font.x = 13,
           fontsize = 3,
           censor.size=0.2, 
           size = 0.2,
           fun = "event",
           surv.scale = "percent") # + theme(axis.text =  element_text(size = 12))

